version: "3.6"

services:
  cassandra:
    container_name: testcass
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    networks:
      - default
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster

  redis:
    container_name: redis_chat 
    image: 'redis:7.0.2'
    ports:
      - "6379:6379" 
    networks:
      - default  

networks:
  default:
    driver: bridge
